onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_dlx/DLX_0/clock
add wave -noupdate /tb_dlx/DLX_0/reset
add wave -noupdate /tb_dlx/DLX_0/DRAM_RE_byp
add wave -noupdate /tb_dlx/DLX_0/DRAM_WE_byp
add wave -noupdate /tb_dlx/DLX_0/DRAM_ADD_byp
add wave -noupdate /tb_dlx/DLX_0/DRAM_DIN_byp
add wave -noupdate /tb_dlx/DLX_0/DRAM_Dout_byp
add wave -noupdate /tb_dlx/DLX_0/IRAMout
add wave -noupdate /tb_dlx/DLX_0/PC_out
add wave -noupdate /tb_dlx/DLX_0/DRAM_RE_byp_sig
add wave -noupdate /tb_dlx/DLX_0/DRAM_WE_byp_sig
add wave -noupdate /tb_dlx/DLX_0/DRAM_ADD_byp_sig
add wave -noupdate /tb_dlx/DLX_0/DRAM_DIN_byp_sig
add wave -noupdate /tb_dlx/DLX_0/DRAM_Dout_byp_sig
add wave -noupdate /tb_dlx/DLX_0/IRAMout_sig
add wave -noupdate /tb_dlx/DLX_0/PC_out_sig
add wave -noupdate /tb_dlx/DLX_0/not_clock
add wave -noupdate /tb_dlx/DLX_0/s_IR_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/s_NPC_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/s_RegA_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/s_RegB_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/s_RegIMM_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/s_muxsign_sel
add wave -noupdate /tb_dlx/DLX_0/s_muximm_jvsimm
add wave -noupdate /tb_dlx/DLX_0/s_R_VS_IMM_J
add wave -noupdate /tb_dlx/DLX_0/s_MUXB_SEL
add wave -noupdate /tb_dlx/DLX_0/s_ALU_OUTREG_EN
add wave -noupdate /tb_dlx/DLX_0/s_EQ_COND
add wave -noupdate /tb_dlx/DLX_0/s_will_modify
add wave -noupdate /tb_dlx/DLX_0/s_STORE_MUX
add wave -noupdate /tb_dlx/DLX_0/s_ALU_OPCODE
add wave -noupdate /tb_dlx/DLX_0/s_DRAM_RE
add wave -noupdate /tb_dlx/DLX_0/s_DRAM_WE
add wave -noupdate /tb_dlx/DLX_0/s_LMD_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/s_JUMP_BRANCH
add wave -noupdate /tb_dlx/DLX_0/s_JUMP_EN
add wave -noupdate /tb_dlx/DLX_0/s_PC_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/s_JAL_SIG
add wave -noupdate /tb_dlx/DLX_0/s_WB_MUX_SEL
add wave -noupdate /tb_dlx/DLX_0/s_RF_WE
add wave -noupdate /tb_dlx/DLX_0/s_IR_IN
add wave -noupdate /tb_dlx/DLX_0/s_PC_out
add wave -noupdate /tb_dlx/DLX_0/s_cu_in
add wave -noupdate /tb_dlx/DRAM_0/Rst
add wave -noupdate /tb_dlx/DRAM_0/WR_enable
add wave -noupdate /tb_dlx/DRAM_0/R_enable
add wave -noupdate /tb_dlx/DRAM_0/clock
add wave -noupdate /tb_dlx/DRAM_0/Addr
add wave -noupdate /tb_dlx/DRAM_0/Din
add wave -noupdate /tb_dlx/DRAM_0/Dout
add wave -noupdate /tb_dlx/DRAM_0/DRAM_mem
add wave -noupdate /tb_dlx/IRAM_0/Rst
add wave -noupdate /tb_dlx/IRAM_0/clock
add wave -noupdate /tb_dlx/IRAM_0/Addr
add wave -noupdate /tb_dlx/IRAM_0/Dout
add wave -noupdate /tb_dlx/IRAM_0/IRAM_mem
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/CLK
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/RESET
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/ENABLE
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/RD1
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/RD2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/WR
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/ADD_WR
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/ADD_RD1
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/ADD_RD2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/DATAIN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/OUT1
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/OUT2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/RET_ADD
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/JAL_SIG
add wave -noupdate /tb_dlx/DLX_0/datapath_1/register_file_0/REGISTERS
add wave -noupdate /tb_dlx/DLX_0/datapath_1/clk
add wave -noupdate /tb_dlx/DLX_0/datapath_1/reset
add wave -noupdate /tb_dlx/DLX_0/datapath_1/IR_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/NPC_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/RegA_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/RegB_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/RegIMM_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/muxsign_sel
add wave -noupdate /tb_dlx/DLX_0/datapath_1/muximm_jvsimm
add wave -noupdate /tb_dlx/DLX_0/datapath_1/R_VS_IMM_J
add wave -noupdate /tb_dlx/DLX_0/datapath_1/JUMP_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/JUMP_BRANCH
add wave -noupdate /tb_dlx/DLX_0/datapath_1/PC_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/JAL_SIG
add wave -noupdate /tb_dlx/DLX_0/datapath_1/EQ_COND
add wave -noupdate /tb_dlx/DLX_0/datapath_1/will_modify
add wave -noupdate /tb_dlx/DLX_0/datapath_1/MUXB_SEL
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ALU_OUTREG_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/STORE_MUX
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ALU_OPCODE
add wave -noupdate /tb_dlx/DLX_0/datapath_1/dram_re
add wave -noupdate /tb_dlx/DLX_0/datapath_1/DRAM_WE
add wave -noupdate /tb_dlx/DLX_0/datapath_1/LMD_LATCH_EN
add wave -noupdate /tb_dlx/DLX_0/datapath_1/LOAD_MUX
add wave -noupdate /tb_dlx/DLX_0/datapath_1/WB_MUX_SEL
add wave -noupdate /tb_dlx/DLX_0/datapath_1/RF_WE
add wave -noupdate /tb_dlx/DLX_0/datapath_1/IRAMout
add wave -noupdate /tb_dlx/DLX_0/datapath_1/PC_out
add wave -noupdate /tb_dlx/DLX_0/datapath_1/DRAM_RE_byp
add wave -noupdate /tb_dlx/DLX_0/datapath_1/DRAM_WE_byp
add wave -noupdate /tb_dlx/DLX_0/datapath_1/DRAM_ADD_byp
add wave -noupdate /tb_dlx/DLX_0/datapath_1/DRAM_DIN_byp
add wave -noupdate /tb_dlx/DLX_0/datapath_1/DRAM_Dout_byp
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ADDPC_out_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/real_PC_out_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/NPC_out_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/NPC_out_delayed
add wave -noupdate /tb_dlx/DLX_0/datapath_1/NPC_out_delayed2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ADDPC_jal_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/IRout
add wave -noupdate /tb_dlx/DLX_0/datapath_1/MUX_BRANCHES_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/PC_OUT_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/PC_OUT_sig2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/pc_mux_sig_delayed
add wave -noupdate /tb_dlx/DLX_0/datapath_1/reg_file_in
add wave -noupdate /tb_dlx/DLX_0/datapath_1/regin1
add wave -noupdate /tb_dlx/DLX_0/datapath_1/reg_mux1
add wave -noupdate /tb_dlx/DLX_0/datapath_1/regin2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/reg_mux2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/imm_mux2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/imm2_delay_mem
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ADD_WR_SIG
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ADD_WR_DEC
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ADD_WR_EX
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ADD_WR_fetch
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ADD_WR_SIG_mux
add wave -noupdate /tb_dlx/DLX_0/datapath_1/imm_j
add wave -noupdate /tb_dlx/DLX_0/datapath_1/imm_unsign
add wave -noupdate /tb_dlx/DLX_0/datapath_1/imm_brorj
add wave -noupdate /tb_dlx/DLX_0/datapath_1/j_imm_cont
add wave -noupdate /tb_dlx/DLX_0/datapath_1/usls_co
add wave -noupdate /tb_dlx/DLX_0/datapath_1/jump_PC
add wave -noupdate /tb_dlx/DLX_0/datapath_1/offset_j
add wave -noupdate /tb_dlx/DLX_0/datapath_1/offset_j_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/s_ADD_A
add wave -noupdate /tb_dlx/DLX_0/datapath_1/s_ADD_B
add wave -noupdate /tb_dlx/DLX_0/datapath_1/valid_out
add wave -noupdate /tb_dlx/DLX_0/datapath_1/validate_out
add wave -noupdate /tb_dlx/DLX_0/datapath_1/real_register1
add wave -noupdate /tb_dlx/DLX_0/datapath_1/real_register2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/reg_alu_out
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ALUout
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ALUin1
add wave -noupdate /tb_dlx/DLX_0/datapath_1/ALUin2
add wave -noupdate /tb_dlx/DLX_0/datapath_1/pc_mux_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/not_comp_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/comp_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/branch_out_sig
add wave -noupdate /tb_dlx/DLX_0/datapath_1/branch_out_delayed
add wave -noupdate /tb_dlx/DLX_0/datapath_1/sign_ext_delay
add wave -noupdate /tb_dlx/DLX_0/datapath_1/regb_bypass
add wave -noupdate /tb_dlx/DLX_0/datapath_1/RET_ADD
add wave -noupdate /tb_dlx/DLX_0/datapath_1/store_data
add wave -noupdate /tb_dlx/DLX_0/datapath_1/DRAMout
add wave -noupdate /tb_dlx/DLX_0/datapath_1/LMDout
add wave -noupdate /tb_dlx/DLX_0/datapath_1/reg_alu_mem
add wave -noupdate /tb_dlx/DLX_0/datapath_1/jump_condition
add wave -noupdate /tb_dlx/DLX_0/datapath_1/not_clk
add wave -noupdate /tb_dlx/DLX_0/datapath_1/rt_vs_it
add wave -noupdate /tb_dlx/DLX_0/s_LOAD_MUX
add wave -noupdate -radix decimal /tb_dlx/DLX_0/datapath_1/imm_sign
add wave -noupdate -radix decimal /tb_dlx/DLX_0/datapath_1/load32
add wave -noupdate -radix decimal /tb_dlx/DLX_0/datapath_1/imm2
add wave -noupdate -radix decimal /tb_dlx/DLX_0/datapath_1/imm2_delay_exec
add wave -noupdate -radix decimal /tb_dlx/DLX_0/datapath_1/imm2_sig
add wave -noupdate -radix decimal /tb_dlx/DLX_0/datapath_1/load_data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {75 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 328
configure wave -valuecolwidth 84
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {4 ns} {166 ns}
